version: "3.8"
services:
  backend:
    build:
      context: ./src/Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    networks:
      - app-network

  frontend:
    build:
      context: ./src/Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"    
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
